apiVersion: v1
kind: ConfigMap
metadata:
  name: "inject-config"
data:
  config.yaml: |
    enable: true       # Whether to enable injection
    proxy_port: 4001   # The proxy port of Dragonfly Dfdaemon
    cli_tools_image: dragonflyoss/toolkits:latest # The image used for injection
    cli_tools_dir_path: /dragonfly-tools          # The tools directory path in the image

